# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fridge.Recipy'),
            preserve_default=False,
        ),
    ]
